version: "3.7"

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django-green_local_django
    depends_on:
      # - mailhog
      # - redis
      - postgres
    volumes:
      - .:/code
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build: ./compose/production/tech/postgres/
    image: django-green_production_postgres
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"

  # mailhog:
  #   image: mailhog/mailhog:v1.0.0
  #   ports:
  #     - "8025:8025"

  # redis:
  #   build: ./compose/production/redis/
  #   container_name: redis
  #   restart: always
