# Generated by Django 3.1.5 on 2021-01-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='provider_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
