databases:
  - cluster_name: db-postgresql-fra1-72665
    db_name: defaultdb
    db_user: doadmin
    engine: PG
    name: db-postgresql-fra1-72665
    production: true
    version: "10"
domains:
  - domain: djangogreen.com
    type: PRIMARY
name: django-version1-saas-builder
region: fra
services:
  - dockerfile_path: compose/production/platform/doap/Dockerfile
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db-postgresql-fra1-72665.DATABASE_URL}
      - key: DJANGO_SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:tpQ95donZpnniNE+tjAx0BRYv8eqn5Cr:6xURygv4M+5My+cofEWs3K2HUsPt5iFJM/iseKk3Ukrc3IMjZaW/4j4jkjinzq3U4a5esA==]
      - key: DJANGO_ALLOWED_HOSTS
        scope: RUN_AND_BUILD_TIME
        value: ${APP_DOMAIN}
      - key: DEBUG
        scope: RUN_AND_BUILD_TIME
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        scope: RUN_AND_BUILD_TIME
        value: composeexample.settings.production
    github:
      branch: follow-eno-a3-django
      deploy_on_push: true
      repo: Oppoin/django-green
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xs
    name: django-version1-saas-builder
    routes:
      - path: /
    run_command: gunicorn --error-logfile /var/log/gunicorn.error --access-logfile /var/log/gunicorn.access --worker-tmp-dir /dev/shm composeexample.wsgi
static_sites:
  - name: static
    envs:
      - key: DATABASE_URL
        scope: BUILD_TIME
        value: ${db-postgresql-fra1-72665.DATABASE_URL}
    github:
      branch: follow-eno-a3-django
      deploy_on_push: true
      repo: Oppoin/django-green
    output_dir: /staticfiles
    routes:
      - path: /static
